### ISSUE TITLE
multiple ssl keys 

### ISSUE THREAD

**Issue by ozbillwang** [jdauphant/ansible-role-ssl-certs#16]
I need manage several ssl keys, how to prepare the var files?

**Comment by ozbillwang** [comment]
ok, seems the task is not written to support `with_items`, have to update it.

**Comment by jdauphant** [comment]
I use multiple times the role with different variables

**Comment by ozbillwang** [comment]
thanks, @jdauphant .

Could you please give me a sample on how to use your module with multiple ssl keys? For example, how to make different variables, such as `ssl_certs_privkey_path`, `ssl_certs_privkey_path`, etc.

The variable names are already fixed.

**Comment by jdauphant** [comment]
I was using it like that :

```
     - role: ssl-certs
       ssl_certs_common_name: "myfirstdomain.com"
     - role: ssl-certs
       ssl_certs_common_name: "myseconddomain.com"
```

You can do something similar

**Comment by ozbillwang** [comment]
Thanks a lot 👍 . ic. So I have to define the variables (not only one) for several times, not bad solution. will have a try.
