### ISSUE TITLE
Support password protected keys via vars_prompt

### ISSUE THREAD

**Issue by pstoll** [jdauphant/ansible-role-ssl-certs#17]
Would you be open to adding support for password protected keys that get decrypted as they get installed?

e.g. some of the ideas in:
- http://red-badger.com/blog/2014/02/28/deploying-ssl-keys-securely-with-ansible/
- https://gist.github.com/charypar/9237634
- https://blog.confirm.ch/deploying-ssl-private-keys-with-ansible/

Would you be open to that? If so let me know, either if its something you'd be open to doing or accepting a PR for. 

Thanks,
 Perry

**Comment by davidmnoriega** [comment]
My use of this role is a combination of storing the cert/key data via variables, not files, and use `ansible-vault` to encrypt the data.

**Comment by jdauphant** [comment]
@pstoll Thanks for the suggestion, I prefer suggest the usage of `ansible-vault`and not complicate the role.
