### ISSUE TITLE
ssl_certs_mode is not used for generated certs

### ISSUE THREAD

**Issue by j4m3s** [jdauphant/ansible-role-ssl-certs#18]
`ssl_certs_path_owner` and `ssl_certs_path_group` are also ignored, the generated certificate is left under the ownership of the ansible user.  

I would have expected that these settings would be applied the same way to generated certificates as well as copied ones.

(NB this applies to dhparam.pem too).

**Comment by jdauphant** [comment]
@j4m3s You have right, thanks for the report. ssl_certs_path_owner and ssl_certs_path_group are ignored for generated certificates and dhparam.pem :(

If you want to do a pull request, it will be welcome :)

**Comment by fpalluel** [comment]
Hello,
Is there a reason why @AlbanAndrieu's fix is not merged in main repo ?

**Comment by jdauphant** [comment]
@Moxide no PR was made

**Comment by jdauphant** [comment]
@Moxide In fact, after verification, it's merged but the fix was made by @mpolci

**Comment by jdauphant** [comment]
Fixed by #21

**Comment by fpalluel** [comment]
I just realized that too !
Thanks :-)
