### ISSUE TITLE
Wrong ssl_certs_privkey_path and ssl_certs_cert_path generated

### ISSUE THREAD

**Issue by lktslionel** [jdauphant/ansible-role-ssl-certs#25]
Hello,

**Given** : this playbook : 
```
---
- hosts: localhost
  become: true
  vars:
    name: "{{ app_name | default('default') }}"
    root_path: "{{ app_root_path }}/{{ name }}"
    domain: "{{ app_domain | default('localhost') }}"
    nginx_user: root
  pre_tasks:
    - debug: msg="name={{name}} root={{root_path}} domain={{domain}}"  
    - debug: msg="Before key={{ssl_certs_privkey_path}} crt={{ssl_certs_cert_path}}"  
  roles:
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: "{{ domain }}"
      no_log: false

  post_tasks:
    - debug: msg="After key={{ssl_certs_privkey_path}} crt={{ssl_certs_cert_path}}"  
```

**When I ran :** 
```bash
ansible-playbook main.yml -c local
```

**Then:**

Expected : 

The self-generated certificates files must be found at : 
```bash
- etc/ssl/localhost/localhost.key
- etc/ssl/localhost/localhost.pem
```

Got: 

```bash
- /etc/ssl/45f28166fed1/45f28166fed1.key
- /etc/ssl/45f28166fed1/45f28166fed1.pem
```

Could you help me please ? 
Regards

**Comment by jdauphant** [comment]
@lktslionel Hello, sorry I just see your issue.
What's the value of your variable "app_domain" ? (is it undefined ?)
In your expected values you have no / at the beginning of the path, is that what you want ? (In that case you should change ssl_certs_path to "etc/ssl/{{ssl_certs_common_name}}"

Also:
- "name", "root_path" are unused in your example 
- your debug command on "ssl_certs_privkey_path" "ssl_certs_cert_path" won't send you values you expect, variables are evaluated on the scope and on the scope of your debug command "ssl_certs_common_name" isn't defined

**Comment by lktslionel** [comment]
Thansk for you reply @jdauphant :)
Great it works fine. I have to had these lines as arguments to the `jdauphant.ssl-certs` role : 
```yaml
  roles:
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: "{{ domain }}"
      ssl_certs_path: "/tmp/{{ssl_certs_common_name}}"
```
You rocks !!! and thankls for sharing your role 👍
