### ISSUE TITLE
Sign generated certificate with SHA-256 by default - maybe allow configurable digest

### ISSUE THREAD

**Issue by trutheddie** [jdauphant/ansible-role-ssl-certs#28]
#12 and its associated PR #15 signed the CSR with SHA-256 instead of SHA-1, which is used by default by the ["Generate self-signed SSL certificate" task](https://github.com/jdauphant/ansible-role-ssl-certs/blob/master/tasks/generate.yml#L15).

Unfortunately, that issue/PR did not result in a certificate signed with SHA256. Self-cigned certs generated by this role are still signed with SHA-1.

The proper change is the following:

```
--- old	2017-02-27 16:16:19.842573598 -0500
+++ new	2017-02-27 16:16:22.282573677 -0500
@@ -1 +1 @@
-command: openssl req -nodes -x509 -days {{ ssl_certs_days }} -in {{ ssl_certs_csr_path }} -key {{ ssl_certs_privkey_path }} -out {{ ssl_certs_cert_path }} -extensions v3_ca creates={{ ssl_certs_cert_path }}
+command: openssl req -nodes -x509 -sha256 -days {{ ssl_certs_days }} -in {{ ssl_certs_csr_path }} -key {{ ssl_certs_privkey_path }} -out {{ ssl_certs_cert_path }} -extensions v3_ca creates={{ ssl_certs_cert_path }}
```

Of course, someone could go one step further and just allow the user to specify the digest. The default should still be something like `sha256`, though.

Chrome calls sites with SHA-1-signed certs insecure, for instance.

https://security.googleblog.com/2014/09/gradually-sunsetting-sha-1.html
https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html

**Comment by jdauphant** [comment]
@trutheddie :+1:  Thanks, I have made a PR to fix that :)
