### ISSUE TITLE
Sometimes you don't want to deploy private key and just the cert

### ISSUE THREAD

**Issue by lakshmi-kannan** [jdauphant/ansible-role-ssl-certs#30]
First, thanks for writing the role! It's super useful. 

I am trying to setup SSL for fluentd and the fluentd aggregator nodes are the ones that need the private key and cert. The forwarder just needs the cert. I am sure there are other cases where the cert alone is sufficient for pure clients and they don't need private key.

This "and" condition seems less ideal. 
https://github.com/jdauphant/ansible-role-ssl-certs/blob/master/tasks/main.yml#L64

I changed that condition to ```when: item.content != ''``` and it skips just the part that is empty. I can open a PR. Wdyt?

**Comment by jdauphant** [comment]
Good idea ! You can suggest a PR.

Also, I was thinking doing the same for task "Copy SSL certificates" but it's not that easy (we have to split the task and remove the "with_items")
