### ISSUE TITLE
Combine key and cert fails with wildcard certificates

### ISSUE THREAD

**Issue by uplexPaul** [jdauphant/ansible-role-ssl-certs#40]
If  ssl_certs_common_name contains an asterisk for getting a wildcard certificate (like "*.mydomain.com") the step "Combine key and cert" will fail because the wildcard in the regex isn't properly escaped.

**Comment by uplexPaul** [comment]
Here is a pull request
https://github.com/jdauphant/ansible-role-ssl-certs/pull/41

**Comment by jdauphant** [comment]
Thanks ;)
