### ISSUE TITLE
'ssl_certs_local_cert_data' is undefined with Ansible 2

### ISSUE THREAD

**Issue by jdauphant** [jdauphant/ansible-role-ssl-certs#6]
Apparently update from Ansible 1.9 to 2.0 break the usage of ssl_certs_local_cert_data

**Comment by Plopix** [comment]
@jdauphant ;-) (PR #11)

**Comment by timzhang926** [comment]
Can you please help to push this update to ansible galaxy to enable uses to pick it up. Thank a lot.

**Comment by Plopix** [comment]
Hey, waiting the publication on Ansible Galaxy I used this workaround:

```
- src: https://github.com/jdauphant/ansible-role-ssl-certs
  version: v1.2.2
  name: jdauphant.ssl-certs
```

hope it can help.

++

**Comment by jdauphant** [comment]
@zhangxd926 @Plopix Done
